_wandb:
    value:
        cli_version: 0.22.2
        e:
            wwmlxdse8m0mzah0m5znqctkflvv0xjf:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "7516192768"
                args:
                    - --run=
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "175432232960"
                email: ws18022@outlook.com
                executable: /Users/wangshuo/Desktop/mychat/.venv/bin/python
                git:
                    commit: 63fd4719ddabe31fa81b84f93970209342f6ec36
                    remote: git@github.com:mileswangs/mychat.git
                host: wangshuodeMacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-14.6.1-arm64-arm-64bit
                program: -m scripts.chat_rl
                python: CPython 3.10.16
                root: /Users/wangshuo/Desktop/mychat
                startedAt: "2025-11-02T09:41:36.653219Z"
                writerId: wwmlxdse8m0mzah0m5znqctkflvv0xjf
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 49
                - 51
            "2":
                - 1
                - 49
                - 51
            "3":
                - 13
                - 16
            "4": 3.10.16
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
device_batch_size:
    value: 8
device_type:
    value: mps
dtype:
    value: bfloat16
embedding_lr:
    value: 0.2
eval_every:
    value: 60
eval_examples:
    value: 400
examples_per_step:
    value: 16
init_lr_frac:
    value: 0.05
matrix_lr:
    value: 0.02
max_new_tokens:
    value: 256
num_epochs:
    value: 1
num_samples:
    value: 16
run:
    value: ""
save_every:
    value: 60
source:
    value: sft
temperature:
    value: 1
top_k:
    value: 50
unembedding_lr:
    value: 0.004
weight_decay:
    value: 0
